spring.application.name=Talk-To-Past-Self

gemini.api.key=${GEMINI_API_KEY}

spring.datasource.url=jdbc:postgresql://localhost:5432/past-self
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
